#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Nov 28 12:15:24 2020

@author: vishali
"""

class CDIPlayerType:
    def _init_(self, p_cdi=(0.5,0.5,0.5), p_human = (0.0,0.0,0.0)):
        self.p_cdi = p_cdi
        self.p_human = p_human
    def move(self, player, game):
        # get opponent and learn her last move
        opponent = game.opponents[player]
        last_move = game.get_last_move(opponent)
        # respond to opponent's last move
        if last_move is None:
            p_defect = self.p_cdi[-1]
        else:
            p_defect = self.p_cdi[last_move]
        return random.uniform(0,1) < p_defect
    
    def strat(self, human, game):
        answer = input("What is your response?: ")
        if last_move is None:
            if answer == "C":
                p_defect = self.p_human[-1]
            else:
                p_defect = 1
        else:
            if answer == "C":
                p_defect = 0
            else:
                p_defect = 1
        return random.uniform(0,1) < self.p_human
      
        
      
        
      if last_move is None:
           p_defect = answer
        
       
        if answer == "C":
            p_human = (0.0,0.0,0.0)
        elif answer == "D":
            p_human = (1.0,1.0,1,0)
        else:
            print(" Please enter a correct respose")
            answer = input("What is your response?: ")
        return random.uniform(0,1) < self.p_human
